language: rust
env:
  global:
    - REPO=yarner-bib

os:
  - linux
  - windows
  - osx

rust:
  - stable

branches:
  only:
    - main
    - "/^\\d+\\.\\d+\\.\\d+/"

script:
  - rustup component add rustfmt clippy
  - cargo fmt -- --check
  - cargo clippy --all-targets -- --deny warnings
  - cargo test --verbose

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

before_deploy:
  - cargo build --release
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cp -f target/release/${REPO} . > /dev/null;
      tar -czf ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz ${REPO};
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cp -f target/release/${REPO} . > /dev/null;
      tar -czf ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz ${REPO};
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cp -f target/release/${REPO}.exe . > /dev/null;
      tar -czf ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz ${REPO}.exe;
    fi

deploy:
  provider: releases
  skip_cleanup: true
  token:
    secure: BuyipteQit75EgqCSRXSkYx9ev0GfFw4pLNekEb79dhuYBAC+AAeCJHeH7S5hoLgHP4j2ms1PzoElUF96xqtlUQtj0BXnYFASLLl+tiKLCN8XU7LhOR+WcDaHqzvcm525pFzJTn5g30fEKkNriLQHa4vD6NnuJkulZ7vOx03C/xD8xVmbLLJrsu/AreCskk++K11flSX2HNuJT02Cqm/U0kaS9NIJYzEg/VWNTeWijq+BZFCfDpPeAxzhmw9pz5g0WLMjz0N2i+ZcDFvB4AEdP+JEl00YzEZyA83GSV4Uuz8mfbFvcY4iVV0h4s8nzmncjmK4ZsMVQsDlugHhD2ZvQT605TPvfnGb7i4jVrHAu3aVrHQNtYJkQUTbTs0eH1a9cjocbqQkRLrti5HhBEpvxHFFT3YRJhfxQAJozxjHdULYqAAY1qA0GalgTiFFGunKF0yvalK1F4pRbRau28OVR8iXtgaTThOzZN3lJaUOR7y4DobUjJwsoScCPRlQZMxUayQR9Rx0j7lwaQvMxez1OZwq/le211CzNAbDdeu95D21DdES8MIbGRacAD8Lqs5p1+iEKEftcEJOqMMXl7L8m73FDxIJ9KZUR1xAQGVTG/qMe81YonXyy+GgKYvzLzyUt30m3CTERYYR3N+OpHH193eS8Nbbd8n2FDAxbu+2oE=
  file: ${REPO}-${TRAVIS_TAG}-${TRAVIS_OS_NAME}.tar.gz
  on:
    tags: true
    all_branches: true
