[package]
name = "yarner-bib"
version = "0.1.0"
authors = ["Martin Lange <martin_lange_@gmx.net>"]
edition = "2018"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
yarner-lib = { git = "https://github.com/mlange-42/yarner.git", tag = "0.5.0" }
